#spring.application.name=agentic-AI-demo
spring:
  application:
    name: agentic-AI-demo
  thymeleaf:
    check-template-location: true
  ai:
    ollama:
      chat:
        model: llama3.1:8b
#        model: llama3.2:3b
#        model: hf.co/Salesforce/xLAM-1b-fc-r-gguf
#        model: hf.co/Salesforce/xLAM-1b-fc-r
      init:
        pull-model-strategy: when_missing
        options:
          temperature: 0.1
  datasource:
    url: jdbc:postgresql://localhost:5432/dossiers_remboursements
  docker:
    compose:
      file: src/main/docker/compose.yml

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
#    com.zenika.demo.ai.agentic.agenticaidemo.api.ConversationController: debug
#    org.springframework.web.client.DefaultRestClient: debug
#    org.springframework.web.reactive.function.client.ExchangeFunctions: debug

dossier-remboursement:
  sql-system-prompt: classpath:prompts/dossier-remboursement-sql-query-system-prompt.md
  system-prompt: classpath:prompts/dossier-remboursement-system-prompt.md
